export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.webp',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/lotus5.png',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/creative.png',
        prompt:''
    },
]